In [1]:
#Imports
import numpy as np
import pandas as pd
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, precision_score, f1_score, accuracy_score, recall_score, precision_recall_curve, roc_curve
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
import matplotlib as mpl
import matplotlib.pyplot as plt

#CHANGE THESE FILEPATHS TO THE PLACE WHERE THEY ARE STORED
#VERY IMPORTANT
#Reading Data and Tags
train_data_raw = pd.read_csv("D:/Users/Owner/Desktop/AI/Project/datasets/train_sorted_data.csv")
train_data_target = pd.read_csv("D:/Users/Owner/Desktop/AI/Project/datasets/train_sorted_labels.csv")
test_data_raw = pd.read_csv("D:/Users/Owner/Desktop/AI/Project/datasets/test.csv")

In [2]:
#Convert data to 0-7 instead of 0-255
train_data = train_data_raw.floordiv(32)
test_data = test_data_raw.floordiv(32)
#Split into training and test sets
train_X, test_X, train_y, test_y = train_test_split(train_data, train_data_target, test_size=0.33)

In [3]:
#Create the Neural Net, 3 hidden layers of 100 nodes each
mlp = MLPClassifier(hidden_layer_sizes=(100, 100, 100), max_iter=500, verbose='True')
#Train the data
mlp.fit(train_X, train_y)

c:\users\owner\appdata\local\programs\python\python37\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:916: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Iteration 1, loss = 0.47566349
Iteration 2, loss = 0.16491123
Iteration 3, loss = 0.10612521
Iteration 4, loss = 0.07558897
Iteration 5, loss = 0.05832862
Iteration 6, loss = 0.04121074
Iteration 7, loss = 0.03358825
Iteration 8, loss = 0.02548321
Iteration 9, loss = 0.01890963
Iteration 10, loss = 0.01577751
Iteration 11, loss = 0.01039848
Iteration 12, loss = 0.01032879
Iteration 13, loss = 0.01635349
Iteration 14, loss = 0.01771555
Iteration 15, loss = 0.00945757
Iteration 16, loss = 0.01040311
Iteration 17, loss = 0.01379225
Iteration 18, loss = 0.01175738
Iteration 19, loss = 0.02361364
Iteration 20, loss = 0.00875118
Iteration 21, loss = 0.00514106
Iteration 22, loss = 0.00410992
Iteration 23, loss = 0.00638870
Iteration 24, loss = 0.02018582
Iteration 25, loss = 0.01733590
Iteration 26, loss = 0.01798086
Iteration 27, loss = 0.01067533
Iteration 28, loss = 0.00433435
Iteration 29, loss = 0.00116269
Iteration 30, loss = 0.00034067
Iteration 31, loss = 0.00026308
Iteration 32, los

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100, 100, 100), learning_rate='constant',
       learning_rate_init=0.001, max_iter=500, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose='True', warm_start=False)

In [4]:
#Training accuracy
print("Training set score: %f" % mlp.score(train_X, train_y))

Training set score: 1.000000


In [5]:
#Test accuracy
print("Test set score: %f" % mlp.score(test_X, test_y))

Test set score: 0.973232


In [10]:
#Make a confusion matrix
y_pred = mlp.predict(train_X)

print("Confusion Matrix:")
print(confusion_matrix(train_y, y_pred))


Confusion Matrix:
[[2267    1   19   24   89   82  168    0  130   27]
 [   0 3081    9    4    0    3   29   35   30   13]
 [  63  122 1919  101   89   14  152   50  173  104]
 [  42   31   90 1773   12  211  145   58  326  213]
 [   0   89    7    0 1685    4   97    2   88  713]
 [  40  202   32  296  108  740  280   10  433  422]
 [  86   17  128    2  244   22 2203    0   31   10]
 [  14   76   21    1  196   25    6 1519   19 1039]
 [  21  129   26   67   55   64   44    8 1871  422]
 [   7   29    1   16  250   13   15   75   55 2366]]
